### ISSUE TITLE
Installation Problem

### ISSUE THREAD

**Issue by kateerine** [marlonecobos/kuenm2#1]
Hi,
I'm facing this error when I tried to install this package. I already installed rtools, maxent and java but still the problem persists. 

 installation of package ‘C:/Users/Admin/AppData/Local/Temp/RtmpeaSXSo/file232c324543c4/kuenm2_0.0.7.tar.gz’ had non-zero exit status

**Comment by marlonecobos** [comment]
Sorry but `kuenm2` is only in its initial phase of development. You may want to install `kuenm` instead.
